### ISSUE TITLE
run failed in project jEdit

### ISSUE THREAD

**Issue by xzm2000** [mahnooshshd/extract_method#4]
```
on 808: method add_escapes of class ParseException has been refactored
on 808: ----------------------------------
|███████▏                                | ▃▁▃ 810/4537 [18%] in 1:47:16 (0.1/s, eta: 8:11:22)Traceback (most recent call last):
  File "main.py", line 168, in <module>
    main()
  File "main.py", line 118, in main
    function_refactoring_res = get_candidate_refactorings(function[-1], function[-2], project_path)
  File "/Users/xzm/extract_method/extract_refactoring_candidates.py", line 125, in get_candidate_refactorings
    graph = get_code_graph(method_name, class_name, project_path)
  File "/Users/xzm/extract_method/source_code_parser.py", line 344, in get_code_graph
    if_line_number = dependent_blocks[-1][1]
IndexError: list index out of range
```

I use python 3.7.12 and command `python main.py jEdit /Users/xxxxx/extract_method/jEdit/jedit.jar` to run this code. After an hour, it puts the information.
How can I solve this problem or get the refactored information before error?

**Comment by ZICXR** [comment]
我也遇到了这个问题，怎么解决？

**Comment by mern4k** [comment]
I had the same issue with freemind project, try using Python 3.8.0. Though I haven't run it on jEdit, so it may not help
